### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by tombrowndev** [tombrowndev/react-touch-visualizer#4]
We are in need of an official logo! Can anyone help?

Requirement: Cool looking 😎

**Comment by M4yankChoudhary** [comment]
I can help in making the logo.

**Comment by M4yankChoudhary** [comment]
what will be the title of the logo ?

**Comment by tombrowndev** [comment]
Hi @M4yankChoudhary 

That would be great!

The title would be: React Touch Visualizer

**Comment by M4yankChoudhary** [comment]
![Logo](https://user-images.githubusercontent.com/42598915/95453734-02f96380-0989-11eb-9b8d-11c5c369c862.png)

one more

**Comment by tombrowndev** [comment]
I like it!

Thanks @M4yankChoudhary

**Comment by M4yankChoudhary** [comment]
You're welcome @tombrowndev 🤞☺️

**Comment by tombrowndev** [comment]
Can I credit you in the Readme @M4yankChoudhary ?

**Comment by M4yankChoudhary** [comment]
Sure @tombrowndev

**Comment by M4yankChoudhary** [comment]
Yes, But it's your choice. I'm glad I could be of help. @tombrowndev

**Comment by M4yankChoudhary** [comment]
Thanks for the credit. @tombrowndev
